server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  application:
    name: discovery-server-eureka

logging:
  level:
    com:
      netflix:
        eureka: DEBUG
        discovery: DEBUG

